# Generated by Django 3.0.6 on 2020-05-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referrer_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
