# Generated by Django 3.0.6 on 2020-05-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200510_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='to_wallet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
