# Generated by Django 3.0.6 on 2020-05-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
