# Generated by Django 3.0.6 on 2020-05-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200512_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='to_wallet',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
