# Generated by Django 3.0.6 on 2020-05-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200513_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='xthegpqm', max_length=100, unique=True),
        ),
    ]
