# Generated by Django 3.0.6 on 2020-05-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200513_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='ypqrufkp', max_length=100, unique=True),
        ),
    ]
