# Generated by Django 3.0.6 on 2020-06-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200513_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='bheczwci', max_length=100, unique=True),
        ),
    ]
