# Generated by Django 3.0.6 on 2020-05-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20200511_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='summary',
            field=models.CharField(choices=[('transfer', 'transfer'), ('deposit', 'deposit'), ('withdrawal', 'withdrawal')], default='deposit', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('transfer', 'transfer'), ('deposit', 'deposit'), ('withdrawal', 'withdrawal')], max_length=250),
        ),
    ]
