# Generated by Django 3.0.6 on 2020-05-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20200512_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=250),
        ),
    ]
