# Generated by Django 3.0.6 on 2020-06-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20200601_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.CharField(choices=[('luno', 'luno'), ('coinbase', 'coinbase')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
